// <auto-generated />
namespace Cel.Modelo.Persistencia.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class empresa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(empresa));
        
        string IMigrationMetadata.Id
        {
            get { return "201704070054296_empresa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
